version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=80
    ports:
      - "5000:80"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: xpressdb
      POSTGRES_USER: xpressuser
      POSTGRES_PASSWORD: xpresspassword
    ports:
      - "5432:5432"
